FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY gradlew .
COPY gradle gradle/
COPY build.gradle.kts .
COPY settings.gradle.kts .

COPY src src/
RUN ./gradlew bootJar

EXPOSE 8080

CMD sh -c 'java -jar build/libs/*.jar'
