apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: petclinic
  type: LoadBalancer
