apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: petclinic
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
