apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_USER
              value: {{ .Values.db.username }}
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
          image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
          name: {{ .Values.db.name }}
          ports:
            - containerPort: {{ .Values.db.port }}
      restartPolicy: Always
