apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "port"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Values.db.name }}
  type: {{ .Values.db.serviceType }}
